#! /bin/bash

APIS="Common FullNode StorageMiner Gateway Wallet Worker"
__dirname="$(CDPATH= cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd $__dirname

output="${__dirname}/../mainnet/gen/index.js"
echo "Working ..."

echo -e '// Code generated by github.com/filecoin-shipyard/js-lotus-client-schema/go-schemagen. DO NOT EDIT.\n' > ${output}

for api in $APIS; do
  echo -n "const ${api}Methods = " >> ${output}
  go run . $api >> ${output}
  echo -e "\n" >> ${output}
  echo " ... ${api}"
done

echo "module.exports = { $(echo $APIS | sed -E 's/\w+/&Methods/g' | sed 's/ /, /g') }" >> ${output}

echo "Wrote generated API to ${output}, use 'standard --fix' to reformat"
