const commonMethods = {
  AuthNew: {},
  AuthVerify: {},
  Closing: {},
  ID: {},
  LogList: {},
  LogSetLevel: {},
  NetAddrsListen: {},
  NetConnect: {},
  NetConnectedness: {},
  NetDisconnect: {},
  NetFindPeer: {},
  NetPeers: {},
  NetPubsubScores: {},
  Shutdown: {},
  Version: {}
}

const nodeMethods = {
  AuthNew: {},
  AuthVerify: {},
  ChainExport: {},
  ChainGetBlock: {},
  ChainGetBlockMessages: {},
  ChainGetGenesis: {},
  ChainGetMessage: {},
  ChainGetNode: {},
  ChainGetParentMessages: {},
  ChainGetParentReceipts: {},
  ChainGetPath: {},
  ChainGetRandomness: {},
  ChainGetTipSet: {},
  ChainGetTipSetByHeight: {},
  ChainHasObj: {},
  ChainHead: {},
  ChainNotify: {
    subscription: true
  },
  ChainReadObj: {},
  ChainSetHead: {},
  ChainStatObj: {},
  ChainTipSetWeight: {},
  ClientCalcCommP: {},
  ClientFindData: {},
  ClientGenCar: {},
  ClientGetDealInfo: {},
  ClientHasLocal: {},
  ClientImport: {},
  ClientListDeals: {},
  ClientListImports: {},
  ClientMinerQueryOffer: {},
  ClientQueryAsk: {},
  ClientRetrieve: {},
  ClientStartDeal: {},
  Closing: {},
  ID: {},
  LogList: {},
  LogSetLevel: {},
  MarketEnsureAvailable: {},
  MinerCreateBlock: {},
  MinerGetBaseInfo: {},
  MpoolEstimateGasPrice: {},
  MpoolGetNonce: {},
  MpoolPending: {},
  MpoolPush: {},
  MpoolPushMessage: {},
  MpoolSub: {},
  MsigApprove: {},
  MsigCancel: {},
  MsigCreate: {},
  MsigGetAvailableBalance: {},
  MsigPropose: {},
  NetAddrsListen: {},
  NetConnect: {},
  NetConnectedness: {},
  NetDisconnect: {},
  NetFindPeer: {},
  NetPeers: {},
  NetPubsubScores: {},
  PaychAllocateLane: {},
  PaychClose: {},
  PaychGet: {},
  PaychList: {},
  PaychNewPayment: {},
  PaychStatus: {},
  PaychVoucherAdd: {},
  PaychVoucherCheckSpendable: {},
  PaychVoucherCheckValid: {},
  PaychVoucherCreate: {},
  PaychVoucherList: {},
  PaychVoucherSubmit: {},
  Shutdown: {},
  StateAccountKey: {},
  StateAllMinerFaults: {},
  StateCall: {},
  StateChangedActors: {},
  StateCompute: {},
  StateGetActor: {},
  StateGetReceipt: {},
  StateListActors: {},
  StateListMessages: {},
  StateListMiners: {},
  StateLookupID: {},
  StateMarketBalance: {},
  StateMarketDeals: {},
  StateMarketParticipants: {},
  StateMarketStorageDeal: {},
  StateMinerAvailableBalance: {},
  StateMinerDeadlines: {},
  StateMinerFaults: {},
  StateMinerInfo: {},
  StateMinerInitialPledgeCollateral: {},
  StateMinerPower: {},
  StateMinerProvingDeadline: {},
  StateMinerProvingSet: {},
  StateMinerRecoveries: {},
  StateMinerSectorCount: {},
  StateMinerSectors: {},
  StateNetworkName: {},
  StatePledgeCollateral: {},
  StateReadState: {},
  StateReplay: {},
  StateSearchMsg: {},
  StateSectorGetInfo: {},
  StateSectorPreCommitInfo: {},
  StateWaitMsg: {},
  SyncCheckBad: {},
  SyncIncomingBlocks: {},
  SyncMarkBad: {},
  SyncState: {},
  SyncSubmitBlock: {},
  Version: {},
  WalletBalance: {},
  WalletDefaultAddress: {},
  WalletDelete: {},
  WalletExport: {},
  WalletHas: {},
  WalletImport: {},
  WalletList: {},
  WalletNew: {},
  WalletSetDefault: {},
  WalletSign: {},
  WalletSignMessage: {},
  WalletVerify: {}
}

const minerMethods = {
  ActorAddress: {},
  ActorSectorSize: {},
  AuthNew: {},
  AuthVerify: {},
  Closing: {},
  DealsConsiderOfflineRetrievalDeals: {},
  DealsConsiderOfflineStorageDeals: {},
  DealsConsiderOnlineRetrievalDeals: {},
  DealsConsiderOnlineStorageDeals: {},
  DealsImportData: {},
  DealsList: {},
  DealsPieceCidBlocklist: {},
  DealsSetConsiderOfflineRetrievalDeals: {},
  DealsSetConsiderOfflineStorageDeals: {},
  DealsSetConsiderOnlineRetrievalDeals: {},
  DealsSetConsiderOnlineStorageDeals: {},
  DealsSetPieceCidBlocklist: {},
  ID: {},
  LogList: {},
  LogSetLevel: {},
  MarketGetAsk: {},
  MarketImportDealData: {},
  MarketListDeals: {},
  MarketListIncompleteDeals: {},
  MarketSetAsk: {},
  MiningBase: {},
  NetAddrsListen: {},
  NetConnect: {},
  NetConnectedness: {},
  NetDisconnect: {},
  NetFindPeer: {},
  NetPeers: {},
  NetPubsubScores: {},
  PledgeSector: {},
  SectorMarkForUpgrade: {},
  SectorRemove: {},
  SectorStartSealing: {},
  SectorsList: {},
  SectorsRefs: {},
  SectorsStatus: {},
  SectorsUpdate: {},
  Shutdown: {},
  StorageAddLocal: {},
  StorageAttach: {},
  StorageBestAlloc: {},
  StorageDeclareSector: {},
  StorageDropSector: {},
  StorageFindSector: {},
  StorageInfo: {},
  StorageList: {},
  StorageLocal: {},
  StorageLock: {},
  StorageReportHealth: {},
  StorageStat: {},
  StorageTryLock: {},
  Version: {},
  WorkerConnect: {},
  WorkerStats: {}
}

const fullNode = {
  methods: {
    ...commonMethods,
    ...nodeMethods
  }
}

const storageMiner = {
  methods: {
    ...commonMethods,
    ...minerMethods
  }
}

module.exports = { fullNode, storageMiner }
