const commonMethods = {
  "AuthNew": {},
  "AuthVerify": {},
  "ID": {},
  "LogList": {},
  "LogSetLevel": {},
  "NetAddrsListen": {},
  "NetConnect": {},
  "NetConnectedness": {},
  "NetDisconnect": {},
  "NetFindPeer": {},
  "NetPeers": {},
  "Version": {}
}

const nodeMethods = {
  "AuthNew": {},
  "AuthVerify": {},
  "ChainExport": {},
  "ChainGetBlock": {},
  "ChainGetBlockMessages": {},
  "ChainGetGenesis": {},
  "ChainGetMessage": {},
  "ChainGetNode": {},
  "ChainGetParentMessages": {},
  "ChainGetParentReceipts": {},
  "ChainGetPath": {},
  "ChainGetRandomness": {},
  "ChainGetTipSet": {},
  "ChainGetTipSetByHeight": {},
  "ChainHasObj": {},
  "ChainHead": {},
  "ChainNotify": {
    "subscription": true
  },
  "ChainReadObj": {},
  "ChainSetHead": {},
  "ChainStatObj": {},
  "ChainTipSetWeight": {},
  "ClientCalcCommP": {},
  "ClientFindData": {},
  "ClientGenCar": {},
  "ClientGetDealInfo": {},
  "ClientHasLocal": {},
  "ClientImport": {},
  "ClientListDeals": {},
  "ClientListImports": {},
  "ClientQueryAsk": {},
  "ClientRetrieve": {},
  "ClientStartDeal": {},
  "ID": {},
  "LogList": {},
  "LogSetLevel": {},
  "MarketEnsureAvailable": {},
  "MinerCreateBlock": {},
  "MinerGetBaseInfo": {},
  "MpoolEstimateGasPrice": {},
  "MpoolGetNonce": {},
  "MpoolPending": {},
  "MpoolPush": {},
  "MpoolPushMessage": {},
  "MpoolSub": {},
  "MsigApprove": {},
  "MsigCancel": {},
  "MsigCreate": {},
  "MsigGetAvailableBalance": {},
  "MsigPropose": {},
  "NetAddrsListen": {},
  "NetConnect": {},
  "NetConnectedness": {},
  "NetDisconnect": {},
  "NetFindPeer": {},
  "NetPeers": {},
  "PaychAllocateLane": {},
  "PaychClose": {},
  "PaychGet": {},
  "PaychList": {},
  "PaychNewPayment": {},
  "PaychStatus": {},
  "PaychVoucherAdd": {},
  "PaychVoucherCheckSpendable": {},
  "PaychVoucherCheckValid": {},
  "PaychVoucherCreate": {},
  "PaychVoucherList": {},
  "PaychVoucherSubmit": {},
  "StateAccountKey": {},
  "StateCall": {},
  "StateChangedActors": {},
  "StateCompute": {},
  "StateGetActor": {},
  "StateGetReceipt": {},
  "StateListActors": {},
  "StateListMessages": {},
  "StateListMiners": {},
  "StateLookupID": {},
  "StateMarketBalance": {},
  "StateMarketDeals": {},
  "StateMarketParticipants": {},
  "StateMarketStorageDeal": {},
  "StateMinerAvailableBalance": {},
  "StateMinerDeadlines": {},
  "StateMinerFaults": {},
  "StateMinerInfo": {},
  "StateMinerInitialPledgeCollateral": {},
  "StateMinerPower": {},
  "StateMinerProvingDeadline": {},
  "StateMinerProvingSet": {},
  "StateMinerRecoveries": {},
  "StateMinerSectorCount": {},
  "StateMinerSectors": {},
  "StateNetworkName": {},
  "StatePledgeCollateral": {},
  "StateReadState": {},
  "StateReplay": {},
  "StateSearchMsg": {},
  "StateSectorPreCommitInfo": {},
  "StateWaitMsg": {},
  "SyncCheckBad": {},
  "SyncIncomingBlocks": {},
  "SyncMarkBad": {},
  "SyncState": {},
  "SyncSubmitBlock": {},
  "Version": {},
  "WalletBalance": {},
  "WalletDefaultAddress": {},
  "WalletExport": {},
  "WalletHas": {},
  "WalletImport": {},
  "WalletList": {},
  "WalletNew": {},
  "WalletSetDefault": {},
  "WalletSign": {},
  "WalletSignMessage": {},
  "WalletVerify": {}
}

const minerMethods = {
  "ActorAddress": {},
  "ActorSectorSize": {},
  "AuthNew": {},
  "AuthVerify": {},
  "DealsImportData": {},
  "DealsList": {},
  "ID": {},
  "LogList": {},
  "LogSetLevel": {},
  "MarketImportDealData": {},
  "MarketListDeals": {},
  "MarketListIncompleteDeals": {},
  "MarketSetPrice": {},
  "MiningBase": {},
  "NetAddrsListen": {},
  "NetConnect": {},
  "NetConnectedness": {},
  "NetDisconnect": {},
  "NetFindPeer": {},
  "NetPeers": {},
  "PledgeSector": {},
  "SectorsList": {},
  "SectorsRefs": {},
  "SectorsStatus": {},
  "SectorsUpdate": {},
  "StorageAddLocal": {},
  "StorageAttach": {},
  "StorageBestAlloc": {},
  "StorageDeclareSector": {},
  "StorageDropSector": {},
  "StorageFindSector": {},
  "StorageInfo": {},
  "StorageList": {},
  "StorageLocal": {},
  "StorageReportHealth": {},
  "StorageStat": {},
  "Version": {},
  "WorkerConnect": {},
  "WorkerStats": {}
}


const fullNode = {
  methods: {
    ...commonMethods,
    ...nodeMethods
  }
}

const storageMiner = {
  methods: {
    ...commonMethods,
    ...minerMethods
  }
}

module.exports = { fullNode, storageMiner }
